// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlU0TQr4yhRf3AHo962CKLd7bsTA6JqRs',
    appId: '1:1035517033827:web:a62c91ffc089878ae2a756',
    messagingSenderId: '1035517033827',
    projectId: 'thinksync-2dc60',
    authDomain: 'thinksync-2dc60.firebaseapp.com',
    databaseURL: 'https://thinksync-2dc60-default-rtdb.firebaseio.com',
    storageBucket: 'thinksync-2dc60.firebasestorage.app',
    measurementId: 'G-56340YE7VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY3ezpvn31u9dfalR8SOdJUWQkYs2KyF8',
    appId: '1:1035517033827:android:94cec3b94760c2b7e2a756',
    messagingSenderId: '1035517033827',
    projectId: 'thinksync-2dc60',
    databaseURL: 'https://thinksync-2dc60-default-rtdb.firebaseio.com',
    storageBucket: 'thinksync-2dc60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXCfkDhBjJnb07kzS0AhFBFmy8bF_N2Ls',
    appId: '1:1035517033827:ios:b84eca213b126dafe2a756',
    messagingSenderId: '1035517033827',
    projectId: 'thinksync-2dc60',
    databaseURL: 'https://thinksync-2dc60-default-rtdb.firebaseio.com',
    storageBucket: 'thinksync-2dc60.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXCfkDhBjJnb07kzS0AhFBFmy8bF_N2Ls',
    appId: '1:1035517033827:ios:b84eca213b126dafe2a756',
    messagingSenderId: '1035517033827',
    projectId: 'thinksync-2dc60',
    databaseURL: 'https://thinksync-2dc60-default-rtdb.firebaseio.com',
    storageBucket: 'thinksync-2dc60.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlU0TQr4yhRf3AHo962CKLd7bsTA6JqRs',
    appId: '1:1035517033827:web:f796aa437d7c6bbce2a756',
    messagingSenderId: '1035517033827',
    projectId: 'thinksync-2dc60',
    authDomain: 'thinksync-2dc60.firebaseapp.com',
    databaseURL: 'https://thinksync-2dc60-default-rtdb.firebaseio.com',
    storageBucket: 'thinksync-2dc60.firebasestorage.app',
    measurementId: 'G-5HPVNE0YZT',
  );
}
